default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= Rails.application.credentials.dig(:wearemusik, :username) %>
  password: <%= Rails.application.credentials.dig(:wearemusik, :password) %>

primary_db: &primary_db
  <<: *default
  database: <%= Rails.application.credentials.dig(:wearemusik, :database_development) %>
  host: <%= Rails.application.credentials.dig(:wearemusik, :host) %>
  port: <%= Rails.application.credentials.dig(:wearemusik, :port) %>
  schema_search_path: public

musicbrainz_db: &musicbrainz_db
  <<: *default
  database: <%= Rails.application.credentials.dig(:musicbrainz, :database) %>
  host: <%= Rails.application.credentials.dig(:musicbrainz, :host) %>
  port: <%= Rails.application.credentials.dig(:musicbrainz, :port) %>
  username: <%= Rails.application.credentials.dig(:musicbrainz, :username) %>
  password: <%= Rails.application.credentials.dig(:musicbrainz, :password) %>
  schema_search_path: musicbrainz,public

development:
  primary: *primary_db
  musicbrainz: *musicbrainz_db

production:
  primary: 
    <<: *primary_db
    database: <%= Rails.application.credentials.dig(:wearemusik, :database_production) %>

  musicbrainz: *musicbrainz_db

cache:
    <<: *primary_db
    database: <%= Rails.application.credentials.dig(:wearemusik, :database_production) %>

queue:
    <<: *primary_db
    database: <%= Rails.application.credentials.dig(:wearemusik, :database_production) %>